import Head from "next/head";
import Image from "next/image";
import { AspectRatio } from "~/components/ui/aspect-ratio";

const Home = () => {
  return (
    <>
      <Head>
        <title>Kickstopia</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto h-16 w-full bg-secondary">INI NAVBAR Y</div>
      <main className="container flex h-[calc(100dvh-64px)] flex-col items-center">
        {/* Hero */}
        <section className="flex h-full flex-col items-center">
          <div className="flex flex-col items-center justify-center gap-y-4 py-16">
            <h2 className="text-center text-4xl font-bold">
              Where the Best Kicks Exists
            </h2>
            <h6 className="text-center leading-tight">
              Find your dream sneakers in a place where only the best kicks
              exist.
            </h6>
          </div>
          <AspectRatio className="relative max-w-[500px]" ratio={4 / 3}>
            <Image
              alt="Hero image"
              src="/images/hero.webp"
              fill
              className="object-cover"
            />
            <div className="absolute z-10 h-full w-full bg-gradient-to-t from-background from-5% via-transparent to-background to-95%"></div>
            <div className="absolute z-10 h-full w-full bg-gradient-to-l from-background from-5% via-transparent to-background to-95%"></div>
          </AspectRatio>
        </section>
      </main>
    </>
  );
};

export default Home;
